name: prepwise
services:
  backend:
    container_name: prepwise-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LLM_API_URL: ${LLLM_API_URL}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      NVIDIA_EMBED_API_KEY: ${NVIDIA_EMBED_API_KEY}
      PORT: "8000"
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
    hostname: prepwise
    image: ghcr.io/chanu4321/prepwise-backend:latest
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/chanu4321/projects/prepwise/papers
        target: /app/backend/papers
        bind:
          create_host_path: true
networks:
  default:
    name: nginx-network
    external: true