graph TD
    classDef default fill:#ffffff,stroke:#000000,stroke-width:2px,color:#000000;
    
    Step1(Upload PDF) --> Step2(OCR Processing)
    Step2 --> Step3(Metadata Extraction)
    Step3 --> Step4[(Store in DB)]
    Step4 --> Step5{Available for Search / AI}
